name: "checks"

on:
  push:
    branches: [master]

jobs:
  command-check:
    name: "Command check"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: "Run tests"
      run: |
        sudo apt install -y pv siege
        tests/ci_test.sh

  markdown-lint-check:
    name: "Markdown lint check"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: "Install Node.js 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install markdownlint-cli"
      run: npm install -g markdownlint-cli

    - name: "Create markdownlint configuration file"
      run: |
        echo "{ MD013: false }" > /tmp/markdownlint_config.json

    - name: "Run markdownlint"
      run: find . -path ./node_modules -prune -o -name "*.md" -print0 | xargs -t -0 markdownlint -c /tmp/markdownlint_config.json

  markdown-spell-check:
    name: "Markdown spell check"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: "Install Node.js 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install markdown-spellcheck"
      run: npm install -g markdown-spellcheck

    - name: "Run mdspell"
      run: mdspell '**/*.md' '!**/node_modules/**/*.md' --ignore-numbers --ignore-acronyms --report --en-gb

  markdown-link-check:
    name: "Markdown link check"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
